FROM alpine:edge

# Setup demo environment variables
ENV HOME=/root \
	DEBIAN_FRONTEND=noninteractive \
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8 \
	LC_ALL=C.UTF-8 \
	DISPLAY=:0.0 \
	DISPLAY_WIDTH=1024 \
	DISPLAY_HEIGHT=768

# x11vnc is in testing repo
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Install git, supervisor, VNC, & X11 packages
RUN apk --update --upgrade add \
	bash \
	fluxbox \
	git \
	socat \
	supervisor \
	x11vnc \
	xterm \
	xvfb \
    wget \
	virtualgl

# Clone noVNC from github
RUN git clone https://github.com/kanaka/noVNC.git /root/noVNC \
	&& git clone https://github.com/kanaka/websockify /root/noVNC/utils/websockify \
	&& rm -rf /root/noVNC/.git \
	&& rm -rf /root/noVNC/utils/websockify/.git \
	&& apk del git

# NB Mounted licenses key: wont work missing files
RUN mkdir -p /opt/licenses && \
    cd /opt && \
    apk install hdf5 libcurl qt-webkit && \
    wget http://archives.ensight.com/EnSight102/10.2.3a/Full/EnSight102Full-10.2.3a-linux_2.6_64.tgz && \
    tar zxvf EnSight102Full-10.2.3a-linux_2.6_64.tgz && \
    chown -R root:root /opt/CEI && \
    ln -sf /opt/licenses/slim8.key /opt/CEI/license8 && \
    sync && \
    rm EnSight102Full-10.2.3a-linux_2.6_64.tgz
    
ENV CEI_HOME=/opt/CEI \
    CEI_ARCH=linux_2.6_64 \
    PATH ${CEI_HOME}/bin:${PATH}

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Modify the launch script 'ps -p'
RUN sed -i -- "s/ps -p/ps -o pid | grep/g" /root/noVNC/utils/launch.sh

EXPOSE 8080

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
